import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'row',
    // backgroundColor: '#ffffff', // Substituído em App.js
  },
  sidebar: {
    width: 80,
    // backgroundColor: '#f9fafb', // Substituído em App.js
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 40,
    paddingBottom: 20,
  },
  sidebarBtn: {
    marginVertical: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sidebarBtnInactive: {
    opacity: 0.4,
  },
  main: {
    flex: 1,
  },
  title: {
    fontSize: 48,
    fontWeight: '800',
    color: '#000000',
    marginBottom: 32,
    fontFamily: Platform.select({ ios: 'HelveticaNeue-Bold', android: 'Roboto' }),
  },
  card: {
    // backgroundColor: '#f9fafb', // Substituído em App.js
    borderRadius: 12,
    padding: 24,
    flexDirection: 'column',
    shadowColor: '#000000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    marginBottom: 32,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 8,
  },
  cardText: {
    fontSize: 16,
    color: '#000000',
  },
  profileHeader: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  profileImageWrapper: {
    marginBottom: 10,
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#000000',
  },
  profileInfoSection: {
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  profileInfoLabel: {
    color: '#000000',
    marginBottom: 4,
    fontSize: 16,
  },
  profileInfoValue: {
    fontWeight: '700',
    color: '#000000',
  },
  profileName: {
    fontSize: 28,
    fontWeight: '800',
    color: '#000000',
    fontFamily: Platform.select({ ios: 'HelveticaNeue-Bold', android: 'Roboto' }),
  },
  profileUsername: {
    color: '#000000',
    marginBottom: 0,
    fontSize: 16,
  },
  profileEmail: {
    color: '#000000',
    marginBottom: 0,
    fontSize: 16,
  },
  profileSchool: {
    color: '#000000',
    marginBottom: 0,
    fontSize: 16,
  },
  profileBioSection: {
    marginTop: 12,
    alignItems: 'flex-start',
  },
  profileBio: {
    color: '#000000',
    fontSize: 16,
    marginBottom: 14,
    maxWidth: 540,
  },
  horizontalLine: {
    borderBottomColor: '#E5E7EB',
    borderBottomWidth: 1,
    width: '100%',
    marginVertical: 20,
    alignSelf: 'center',
  },
  button: {
    backgroundColor: '#000000',
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 12,
    alignItems: 'center',
    alignSelf: 'flex-start',
  },
  buttonText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 16,
  },
  input: {
    backgroundColor: '#f3f4f6',
    padding: 12,
    borderRadius: 12,
    marginBottom: 16,
    fontSize: 16,
    color: '#000000',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f0f0f0',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginBottom: 10,
    marginTop: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: '#000000',
    fontWeight: '400',
  },
  searchIcon: {
  },
  noteCard: {
    backgroundColor: '#F0F0F0',
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
    width: 240,
    height: 110,
    justifyContent: 'space-between',
    margin: 5,
    shadowColor: "#000",
    shadowOffset: {
        width: 0,
        height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  alarmCard: {
    backgroundColor: '#E0E0E0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 6,
    borderWidth: 0,
    flex: 1,
  },
  alarmItemContainer: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    paddingRight: 40,
  },
  alarmCardDisabled: {
    opacity: 0.5,
  },
  alarmContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  alarmTimeText: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#000000',
  },
  alarmSubtitleText: {
    fontSize: 14,
    color: '#000000',
  },
  noteText: {
    color: '#000000',
    fontSize: 16,
    marginBottom: 5,
  },
  emptyText: {
    fontSize: 16,
    color: '#000000',
    fontStyle: 'italic',
    marginBottom: 16,
  },
  fab: {
    backgroundColor: '#000000',
    position: 'absolute',
    right: 28,
    bottom: 28,
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  fabText: {
    color: '#ffffff',
    fontSize: 36,
    fontWeight: '800',
  },
  noteInput: {
    flex: 1,
    backgroundColor: '#f3f4f6',
    borderRadius: 14,
    padding: 20,
    textAlignVertical: 'top',
    fontSize: 18,
    color: '#000000',
  },
  modalContainer: {
    flex: 1,
    padding: 24,
    backgroundColor: '#ffffff',
  },
  modalTitle: {
    marginBottom: 20,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000000',
  },
  modalOverlay: {
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  optionMenu: {
    padding: 24,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    elevation: 10,
    shadowColor: '#000000',
    shadowOpacity: 0.04,
    shadowRadius: 12,
    width: '100%',
  },
  optionItem: {
    paddingVertical: 16,
  },
  optionText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#000000',
  },
  deleteFab: {
    position: 'absolute',
    right: 28,
    bottom: 28,
    backgroundColor: '#dc2626',
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#dc2626',
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 6,
  },
  createText: {
    color: '#000000',
    fontWeight: '700',
    fontSize: 18,
  },
  homeImage: {
    width: '100%',
    height: 250,
    borderRadius: 12,
    marginTop: 20,
  },
  backButton: {
    position: 'absolute',
    top: 20,
    left: 20,
    padding: 10,
    zIndex: 10,
  },
  profileTopLeftButtonsContainer: {
    position: 'absolute',
    top: 20,
    left: 20,
    zIndex: 10,
  },
  profileTopRightButtonsContainer: {
    position: 'absolute',
    top: 20,
    right: 20,
    zIndex: 10,
  },
  profileButtonsColumn: {
    alignItems: 'flex-end',
  },
  settingsButton: {
    padding: 10,
  },
  // Estilos para o modal de escolha de tipo de postagem
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    width: '100%',
    maxWidth: 400,
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
  },
  postTypeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  postTypeIcon: {
    marginRight: 16,
    width: 32,
    textAlign: 'center',
  },
  postTypeTextContainer: {
    flex: 1,
    marginRight: 12,
  },
  postTypeTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
  },
  postTypeDescription: {
    fontSize: 13,
    opacity: 0.8,
  },
  cancelButton: {
    marginTop: 16,
    padding: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: {
    fontWeight: '600',
    fontSize: 16,
  },
  settingsMenu: {
    backgroundColor: '#ffffff',
    padding: 24,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    elevation: 10,
    shadowColor: '#000000',
    shadowOpacity: 0.04,
    shadowRadius: 12,
  },
  deleteAlarmButton: {
    position: 'absolute',
    right: 8,
    top: 8,
    backgroundColor: '#ff6347',
    borderRadius: 15,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  headerImagesContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  alarmModalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  
 
  
 
  mainContent: {
    flex: 1,
    padding: 20,
  },
  
 
  
 
 
 
 
 
 
  
 
 
  
  homeScreenContainer: {
    flex: 1,
    width: '100%',
    backgroundColor: 'transparent',
  },
  searchBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f0f0f0',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginBottom: 10,
    marginTop: 10,
  },
  searchBar: {
    flex: 1,
    fontSize: 14,
    color: '#000000',
    fontWeight: '400',
  },
  homePostsContainer: {
    flexGrow: 1,
    paddingTop: 15,
    paddingHorizontal: 20,
    paddingBottom: 100,
  },
  postCard: {
    backgroundColor: '#f9fafb',
    borderRadius: 12,
    padding: 18,
    marginBottom: 16,
    shadowColor: '#000000',
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
    width: '90%',
  },
  postHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  postAuthorAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
  },
  postAuthorName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000000',
  },
  postImage: {
    width: '100%',
    height: 200,
    borderRadius: 12,
    marginBottom: 10,
  },
  postText: {
    fontSize: 16,
    color: '#000000',
  },
  postDescription: {
    fontSize: 14,
    color: '#000000',
    fontWeight: 'bold',
  },
 
  postSquareButton: {
    backgroundColor: '#F0F0F0',
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    width: '48%',
    aspectRatio: 1,
    shadowColor: "#000",
    shadowOffset: {
        width: 0,
        height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  postSquareButtonText: {
    marginTop: 10,
    fontSize: 14,
    fontWeight: 'bold',
    color: '#000000',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: '90%',
    maxWidth: 400,
  },
  modalViewDark: {
    backgroundColor: '#18181b',
  },
  imagePickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#000000',
    padding: 10,
    borderRadius: 5,
    marginBottom: 15,
  },
  imagePickerButtonText: {
    marginLeft: 10,
    fontSize: 16,
    color: '#ffffff',
  },
  selectedImagePreview: {
    width: '100%',
    height: 150,
    resizeMode: 'contain',
    marginBottom: 15,
    borderRadius: 10,
  },
  noImageSelectedText: {
    marginBottom: 15,
    color: '#000000',
    fontSize: 14,
  },
  modalTextInput: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 10,
    padding: 10,
    marginBottom: 15,
    fontSize: 16,
    color: '#000000',
  },
  modalButton: {
    backgroundColor: '#000000',
    borderRadius: 10,
    padding: 12,
    elevation: 2,
    width: '100%',
    alignItems: 'center',
    marginTop: 10,
  },
  modalButtonClose: {
    backgroundColor: '#000000',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  addContentButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    marginLeft: 10,
  },
  addOptionsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#000000',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 10,
    marginBottom: 10,
    width: '100%',
    justifyContent: 'center',
  },
  addOptionsButtonText: {
    marginLeft: 10,
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  addContentOptionsModalContent: {
    backgroundColor: '#ffffff',
    padding: 20,
    borderRadius: 15,
    width: '80%',
    alignItems: 'center',
    position: 'absolute',
    top: '30%',
    alignSelf: 'center',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  tabContainer: {
    flexDirection: 'row',
    marginBottom: 20,
    justifyContent: 'space-around',
    width: '100%',
  },
  tabButton: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 20,
    backgroundColor: '#E5E7EB',
  },
  tabButtonActive: {
    backgroundColor: '#000000',
  },
  tabButtonText: {
    color: '#000000',
    fontWeight: 'bold',
  },
  tabButtonTextActive: {
    color: '#ffffff',
  },
  agendaContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
    padding: 20,
  },
  agendaHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  agendaTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#000000',
  },
  agendaAddButton: {
    backgroundColor: '#000000',
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  agendaAddButtonText: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: 'bold',
  },
  agendaTabContainer: {
    flexDirection: 'row',
    marginBottom: 20,
    justifyContent: 'space-around',
    backgroundColor: '#F3F4F6',
    borderRadius: 10,
    padding: 5,
  },
  agendaTabButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
  },
  agendaTabButtonActive: {
    backgroundColor: '#000000',
  },
  agendaTabButtonText: {
    color: '#000000',
    fontWeight: 'bold',
  },
  agendaTabButtonTextActive: {
    color: '#ffffff',
  },
  agendaList: {
    flex: 1,
  },
  agendaCard: {
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  agendaCardText: {
    fontSize: 16,
    color: '#000000',
    flex: 1,
  },
  agendaCardAlarmTime: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000000',
  },
  agendaCardNoteContent: {
    fontSize: 16,
    color: '#000000',
  },
  agendaActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  agendaActionButton: {
    marginLeft: 10,
    padding: 5,
  },
  agendaNoContent: {
    textAlign: 'center',
    marginTop: 50,
    fontSize: 18,
    color: '#000000',
  },
  agendaSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginBottom: 15,
  },
  agendaSearchInput: {
    flex: 1,
    fontSize: 14,
    color: '#000000',
  },
  agendaSearchIcon: {
    marginRight: 10,
  },
  postiteModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  postiteModalContent: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    width: '90%',
    maxWidth: 500,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  postiteModalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#000000',
  },
  postiteInput: {
    width: '100%',
    height: 120,
    borderColor: '#000000',
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    marginBottom: 20,
    textAlignVertical: 'top',
    fontSize: 16,
    color: '#000000',
  },
  postiteButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
  },
  postiteButton: {
    backgroundColor: '#000000',
    padding: 12,
    borderRadius: 10,
    flex: 1,
    marginHorizontal: 5,
    alignItems: 'center',
  },
  postiteButtonText: {
    color: '#ffffff',
    fontWeight: 'bold',
  },
  profileContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
    padding: 20,
  },
  profileContent: {
    flex: 1,
  },
  profileSection: {
    marginBottom: 20,
    alignItems: 'flex-start',
  },
  profileSectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#000000',
  },
  profileInfoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  profileInfoText: {
    color: '#000000',
    fontSize: 16,
    marginLeft: 8,
  },
  profilePostGrid: {
    marginTop: 20,
  },
  profilePostGridItem: {
    width: '31.33%',
    flexGrow: 0,
    flexShrink: 0,
    aspectRatio: 1,
    backgroundColor: '#F0F0F0',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    overflow: 'hidden',
  },
  profilePostGridImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  profilePostGridTextContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: '#000000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profilePostGridRemoveButton: {
    position: 'absolute',
    top: 5,
    right: 5,
    zIndex: 1,
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderRadius: 12,
    padding: 2,
  },
  profilePostGridColumnWrapper: {
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  postFilterButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignSelf: 'center',
    width: '80%',
    marginBottom: 5,
  },
  filterButton: {
    padding: 0,
    borderRadius: 0,
    backgroundColor: 'transparent',
  },
  filterButtonActive: {
  },
 
 
  passwordInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginBottom: 15,
  },
 
 
  passwordVisibilityToggle: {
    padding: 5,
  },
  addContentOptionsButtonText: {
    marginLeft: 10,
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  colorPreviewContainer: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#000',
    marginRight: 10,
  },
  colorSelectionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
    marginBottom: 10,
  },
  colorSelectionText: {
    fontSize: 16,
  },
  colorPickerModalContent: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    width: '90%',
    maxWidth: 400,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  colorPickerModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  colorOption: {
    width: 40,
    height: 40,
    borderRadius: 20,
    margin: 8,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  selectedColorOption: {
    borderColor: '#007BFF',
  },
  colorOptionsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginBottom: 20,
  },
  confirmColorButton: {
    backgroundColor: '#007BFF',
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 10,
    alignItems: 'center',
  },
  confirmColorButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  cancelColorButton: {
    marginTop: 10,
    backgroundColor: '#6c757d',
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 10,
    alignItems: 'center',
  },
  cancelColorButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  colorPickerButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginTop: 20,
  },
});

export default styles;